#!/bin/bash
# Prevents force-pushing to master

echo -e "===\n>> Talenavi Pre-push Hook: Checking branch name / Mengecek nama branch..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|development)"

if [[ $1 != *"$BRANCH"* ]]
then
  echo -e "\n🚫 Você deve usar (git push origin $BRANCH).\n" && exit 1
fi

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Não é possiver executar push direto na branch> $BRANCH, crie sua branch e abra um PR.\n" && exit 1
fi

echo -e ">> Processo finalizado.\n==="

exit 0